INSERT INTO parametros (id, etiqueta, texto, id_idioma) 
VALUES 
(NULL, 'GENERIC_TITLE', 'Organizador de proyectos', '73'),
(NULL, 'GENERIC_CANCEL', 'Cancelar', '73'),
(NULL, 'HOME_PAGE', 'Inicio', '73'),
(NULL, 'ABOUT_PAGE', 'Nosotros', '73'),
(NULL, 'CONTACT_PAGE', 'Contacto', '73'),
(NULL, 'LOGIN_PAGE', 'Inicia sesión', '73'),
(NULL, 'LOGIN_PAGE_TITLE', 'Inicia sesión', '73'),
(NULL, 'LOGIN_PAGE_EMAIL', 'Email', '73'),
(NULL, 'LOGIN_PAGE_PASSWORD', 'Contraseña', '73'),
(NULL, 'LOGIN_PAGE_PLACEHOLDER_EMAIL', 'Introduce tu email', '73'),
(NULL, 'LOGIN_PAGE_PLACEHOLDER_PASS', 'Introduce tu contraseña', '73'),
(NULL, 'LOGIN_PAGE_AUTOLOGIN_TEXT', 'Mantén la sesión', '73'),
(NULL, 'LOGIN_PAGE_SIGN_IN', 'Entrar', '73'),
(NULL, 'LOGIN_PAGE_SIGN_UP', 'Registrar', '73'),
(NULL, 'SIGN_UP_PAGE', 'Registro', '73'),
(NULL, 'SIGN_UP_PAGE_TITLE', 'Registro de usuario', '73'),
(NULL, 'SIGN_UP_PAGE_EMAIL', 'Email', '73'),
(NULL, 'SIGN_UP_PAGE_PASSWORD', 'Contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_PASSWORD2', 'R.Contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_FULLNAME', 'Nombre', '73'),
(NULL, 'SIGN_UP_PAGE_BIRTHDATE', 'F. Nacimiento', '73'),
(NULL, 'SIGN_UP_PAGE_NIF', 'NIF', '73'),
(NULL, 'SIGN_UP_PAGE_PHONE', 'Teléfono', '73'),
(NULL, 'SIGN_UP_PAGE_COUNTRY', 'País', '73'),
(NULL, 'SIGN_UP_PAGE_STATE', 'Provincia', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_EMAIL', 'Introduce tu email', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_PASSWORD', 'Introduce tu contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_PASSWORD2', 'Repite la contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_FULLNAME', 'Nombre y apellidos', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_BIRTHDATE', 'Fecha de nacimiento', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_NIF', 'NIF', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_PHONE', 'Teléfono', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_COUNTRY', 'País', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_STATE', 'Provincia', '73'),
(NULL, 'SIGN_UP_PAGE_TERMS', 'Términos y condiciones', '73'),
(NULL, 'SIGN_UP_PAGE_SIGNUP', 'Registrarse', '73')