INSERT INTO parametros (id, etiqueta, texto, id_idioma) 
VALUES 
(NULL, 'GENERIC_TITLE', 'Organizador de proyectos', '73'),
(NULL, 'GENERIC_CANCEL', 'Cancelar', '73'),
(NULL, 'HOME_PAGE', 'Inicio', '73'),
(NULL, 'ABOUT_PAGE', 'Nosotros', '73'),
(NULL, 'CONTACT_PAGE', 'Contacto', '73'),
(NULL, 'LOGIN_PAGE', 'Inicia sesión', '73'),
(NULL, 'LOGIN_PAGE_TITLE', 'Inicia sesión', '73'),
(NULL, 'LOGIN_PAGE_EMAIL', 'Email', '73'),
(NULL, 'LOGIN_PAGE_PASSWORD', 'Contraseña', '73'),
(NULL, 'LOGIN_PAGE_PLACEHOLDER_EMAIL', 'Introduce tu email', '73'),
(NULL, 'LOGIN_PAGE_PLACEHOLDER_PASS', 'Introduce tu contraseña', '73'),
(NULL, 'LOGIN_PAGE_AUTOLOGIN_TEXT', 'Mantén la sesión', '73'),
(NULL, 'LOGIN_PAGE_SIGN_IN', 'Identificarse', '73'),
(NULL, 'LOGIN_PAGE_SIGN_UP', 'Registrarse', '73'),
(NULL, 'SIGN_UP_PAGE', 'Registro', '73'),
(NULL, 'SIGN_UP_PAGE_TITLE', 'Registro de usuario', '73'),
(NULL, 'SIGN_UP_PAGE_EMAIL', 'Email', '73'),
(NULL, 'SIGN_UP_PAGE_PASSWORD', 'Contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_PASSWORD2', 'R.Contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_FULLNAME', 'Nombre', '73'),
(NULL, 'SIGN_UP_PAGE_BIRTHDATE', 'F. Nacimiento', '73'),
(NULL, 'SIGN_UP_PAGE_NIF', 'NIF', '73'),
(NULL, 'SIGN_UP_PAGE_PHONE', 'Teléfono', '73'),
(NULL, 'SIGN_UP_PAGE_COUNTRY', 'País', '73'),
(NULL, 'SIGN_UP_PAGE_STATE', 'Provincia', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_EMAIL', 'Introduce tu email', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_PASSWORD', 'Introduce tu contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_PASSWORD2', 'Repite la contraseña', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_FULLNAME', 'Nombre y apellidos', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_BIRTHDATE', 'Fecha de nacimiento', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_NIF', 'NIF', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_PHONE', 'Teléfono', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_COUNTRY', 'País', '73'),
(NULL, 'SIGN_UP_PAGE_PLACEHOLDER_STATE', 'Provincia', '73'),
(NULL, 'SIGN_UP_PAGE_TERMS', 'Leer términos y condiciones', '73'),
(NULL, 'SIGN_UP_PAGE_SIGNUP', 'Aceptar términos y registrarse', '73')
(NULL, 'LOGIN_PAGE_ERROR_LOGIN', 'Error de usuario o contraseña', '73'),
(NULL, 'PANEL_USER', 'Panel de usuario', '73'),
(NULL, 'LEGAL_PAGE', 'Aviso legal', '73'),
(NULL, 'SIGN_UP_PAGE_FATAL_ERROR', 'Error al registrar el nuevo usuario', '73'),
(NULL, 'SIGN_UP_PAGE_WARNING', 'Las contraseñas no coinciden', '73'),
(NULL, 'SIGN_UP_PAGE_SELECT_ONE_MENU', '-- Selecciona un valor --', '73'),
(NULL, 'USER_DROPDOWN_HEADER_PROFILE', 'Perfil', '73'),
(NULL, 'USER_DROPDOWN_HEADER_PROJECTS', 'Proyectos', '73'),
(NULL, 'USER_DROPDOWN_VIEW_PROJECTS', 'Tus proyectos', '73'),
(NULL, 'USER_DROPDOWN_NEW_PROJECT', 'Crear nuevo', '73'),
(NULL, 'USER_DROPDOWN_CONTROL_PANEL', 'Panel de usuario', '73'),
(NULL, 'USER_DROPDOWN_NEW_PASS', 'Cambiar contraseña', '73'),
(NULL, 'USER_DROPDOWN_LOGOUT', 'Cerrar sesión', '73'),
(NULL, 'PANEL_USER_HEADER_CONTROL_PANEL', 'Panel de usuario', '73'),
(NULL, 'PANEL_USER_HEADER_PROJECTS', 'Todos los proyectos', '73'),
(NULL, 'PANEL_USER_LABEL_PROYECTOS', 'Proyectos', '73'),
(NULL, 'PANEL_USER_LABEL_NEW_PROJECT', 'Crear nuevo', '73'),
(NULL, 'PANEL_USER_LABEL_FIND_PROJECT', 'Buscar proyecto', '73'),
(NULL, 'PANEL_USER_LABEL_EDIT_PROFILE', 'Editar perfil', '73'),
(NULL, 'PANEL_USER_LABEL_NO_HAVE_PROJECTS', 'No tienes proyectos creados', '73'),
(NULL, 'PANEL_USER_LABEL_RECOVERY_DELETED', 'Recuperar eliminados', '73')
(NULL, 'USER_DROPDOWN_HEADER_PROFILE', 'Perfil', '73'),
(NULL, 'USER_DROPDOWN_HEADER_PROJECTS', 'Proyectos', '73'),
(NULL, 'USER_DROPDOWN_VIEW_PROJECTS', 'Tus proyectos', '73'),
(NULL, 'USER_DROPDOWN_NEW_PROJECT', 'Crear nuevo', '73'),
(NULL, 'USER_DROPDOWN_CONTROL_PANEL', 'Panel de usuario', '73'),
(NULL, 'USER_DROPDOWN_NEW_PASS', 'Cambiar contraseña', '73'),
(NULL, 'USER_DROPDOWN_LOGOUT', 'Cerrar sesión', '73'),
(NULL, 'PANEL_USER_HEADER_CONTROL_PANEL', 'Panel de usuario', '73'),
(NULL, 'PANEL_USER_HEADER_PROJECTS', 'Todos los proyectos', '73'),
(NULL, 'PANEL_USER_LABEL_PROYECTOS', 'Proyectos', '73'),
(NULL, 'PANEL_USER_LABEL_NEW_PROJECT', 'Crear nuevo', '73'),
(NULL, 'PANEL_USER_LABEL_FIND_PROJECT', 'Buscar proyecto', '73'),
(NULL, 'PANEL_USER_LABEL_EDIT_PROFILE', 'Editar perfil', '73'),
(NULL, 'PANEL_USER_LABEL_NO_HAVE_PROJECTS', 'No tienes proyectos creados', '73'),
(NULL, 'PANEL_USER_LABEL_RECOVERY_DELETED', 'Recuperar eliminados', '73'),
(NULL, 'PANEL_USER_LABEL_VIEW_PROFILE', 'Ver perfil', '73'),
(NULL, 'PROFILE_USER', 'Perfil de usuario', '73'),
(NULL, 'PROFILE_USER_TITLE', 'Datos de perfil', '73'),
(NULL, 'GENERIC_ACCEPT', 'Aceptar', '73'),
(NULL, 'GENERIC_EDIT', 'Editar', '73'),
(NULL, 'GENERIC_BACK', 'Volver', '73'),
(NULL, 'GENERIC_SAVE', 'Guardar', '73'),
(NULL, 'PROFILE_PREFERENCES', 'Configuración del perfil', '73'),
(NULL, 'COMING_SOON', 'Próximamente', '73'),
-- Nuevos
(NULL, 'GENERIC_ERROR_SAVE', 'Error al guardar los cambios', '73'),
(NULL, 'GENERIC_SUCCESS_SAVE', 'Los cambios se han guardado correctamente', '73'),
(NULL, 'GENERIC_ERROR_VALIDATION', 'Error de validación', '73'),
(NULL, 'GENERIC_ERROR_PASSWORD_NO_MATCH', 'Las contraseñas no coinciden.', '73'),
(NULL, 'GENERIC_ERROR_PASSWORD_REQUIRED', 'La contraseña es obligatoria', '73'),
(NULL, 'GENERIC_ERROR_PASSWORD_INVALID', 'La contraseña no es correcta.', '73'),
(NULL, 'PANEL_USER_LABEL_DELETE_ACCOUNT', 'Cerrar tu cuenta', '73'),
(NULL, 'PANEL_USER_LABEL_DELETE_PROJECTS', 'Borrar proyectos', '73'),
(NULL, 'GENERIC_VIEW_PROJECT', 'Ver proyecto', '73'),
(NULL, 'GENERIC_DELETE', 'Eliminar', '73'),
-- ^^^ añadidos ^^^ -----------
INSERT INTO parametros (id, etiqueta, texto, id_idioma) 
VALUES 
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73'),
(NULL, '', '', '73')

-- ALTER TABLES ---
-- ALTER TABLE `usuario` ADD `birth_date` DATE NULL AFTER `flag_activo`;
ALTER TABLE `usuario` ADD `fullname` VARCHAR(150) NOT NULL AFTER `birth_date`;